CREATE TABLE billett(
billettNr INT PRIMARY KEY AUTO_INCREMENT,
film VARCHAR(255) NOT NULL,
antall INT(255) NOT NULL,
fornavn VARCHAR(255) NOT NULL,
etternavn VARCHAR(255) NOT NULL,
telefon INT(8) NOT NULL,
epost VARCHAR(255) NOT NULL
);